# Use imagem base Python
FROM python:3.10-slim

# Defina diretório de trabalho
WORKDIR /app

# Copie requirements e instale dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie o código da app
COPY app/ .

# Exponha a porta 8000
EXPOSE 8000

# Comando para rodar a API com uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]